### ISSUE TITLE
Update for Sidekiq 4.2 and Sidekiq 5

### ISSUE THREAD

**Issue by tmaier** [utgarda/sidekiq-status#101]
9ba329301b489a382baa3321b635d208c190dbe1 states that the gem is currently incompatible with Sidekiq 4.2 (and Sidekiq 5 subsequently)

I can confirm that there are stability issues when using sidekiq-status with Sidekiq 4.2

**Comment by kenaniah** [comment]
Sidekiq 4.2 and 5.x are now supported. If there are specific issues that you are running into with 4.2, please open an issue, and I would be more than happy to dive into those specifically. Thanks!
