### ISSUE TITLE
worker/jid always showing ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper

### ISSUE THREAD

**Issue by steveburkett** [utgarda/sidekiq-status#105]
HI there, 

If i have the queue_adapter on any job

```
(initializers)
class ActionMailer::DeliveryJob
  queue_as :high

  self.queue_adapter = :sidekiq
end
```

in sidekiq-status tab, in the web UI, the worker/jid always shows as ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper, instead of OrderPickupMailer (for this example)
```
class OrderPickupMailer < ActionMailer::Base
```
see https://imgur.com/RfwQ9OR

I think the solution is if the "worker" is "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", to use args["job_class"] in the UI.  

Using sidekiq v5, sidekiq-status v.0.6.0, rails 4.2.7, ruby 2.2.4.

**Comment by kenaniah** [comment]
Actually, the fix is to use `Sidekiq::Job#display_class` as outlined in this patch here: https://github.com/spidrtech/sidekiq-status/commit/0f1074b9550c8f5d72dc11c950535fa5ceedcfd8
