### ISSUE TITLE
provider_job_id is occasionally missing in the job instance

### ISSUE THREAD

**Issue by volkanunsal** [utgarda/sidekiq-status#108]
Hi again,

I have a spec that are occasionally failing testing the presence of `provider_job_id` in the job instance. The `job_id` is available, even when `provider_job_id` is missing, but I have noticed that `job_id` does not return any results when used with `get_all` method. (btw, what is the difference between the two ids?)

```ruby
   it 'includes a provider_job_id' do
      job = UploadResourceCsv.perform_later(args)
      puts job.inspect
      expect(job.provider_job_id).to be_present
    end
```

The job inspection from a failing spec

```
#<UploadResourceCsv:0x007fb86106c248 @arguments=[{:path=>"/Users/newuser/w/citiesense/webapp/tmp/file.csv", :model_name=>"Tenant"}], @job_id="c451e50c-68a5-4631-94f1-ca73f4b6c6c8", @queue_name="default", @priority=nil, @executions=0>
F
```

**Comment by kenaniah** [comment]
`provider_job_id` is an attribute that is provided by ActiveJob. Does your job class extend from `ActiveJob::Base` somewhere in its ancestry? If not, this property will not be available and `job_id` should be used for tracking purposes in its place.

**Comment by volkanunsal** [comment]
Yes it does. The id is there but only sporadically, which makes me uneasy.
Maybe a race condition somewhere.

-- 
*Volkan Unsal*
*Product Engineer*
volkanunsal.com

**Comment by kenaniah** [comment]
Interesting. Could I ask you to build a minimum reproducible test case for us to look at? I’d like to determine if this issue is due to external or internal factors. A link to an example repository that demonstrates the issue would be great.

**Comment by kenaniah** [comment]
@volkanunsal given that it's been 3 weeks, I'm going to close this issue for now given that I can't confirm this without a test case. Please feel free to reply and I'll re-open if you still believe it's an issue with this gem. Thanks!

**Comment by volkanunsal** [comment]
Sorry, I never got around to it. Maybe it's something weird with my setup.
