### ISSUE TITLE
Group by queue on statuses page

### ISSUE THREAD

**Issue by hackmastera** [utgarda/sidekiq-status#109]
It could either be a sortable column or there could even be a separate table for each queue.

With all the jobs together, if you have high- and low- priority queues you can't really tell when a given job may run just by when it was enqueued.

**Comment by kenaniah** [comment]
This sounds like a great idea and I would love to see a PR for this. My initial thoughts are that the queue could be selected from a filterable list when more than 1 queue is detected. Something like:

Queue: [any](#) | [default](#) | **high-pri** | [low-pri](#)

Results could then be filtered by a single queue (if selected) using a query string parameter, default unfiltered for backwards compat. Would you be interested in putting a PR (with tests) together for this?

**Comment by hackmastera** [comment]
Hi, thanks; I like your filter idea to keep the lists cleaner.

I've investigated our use case further and we've decided to go a different direction, integrating some status info into search results instead of using the dashboard. So I won't be able to work on a PR. Feel free to close as wontfix.
