### ISSUE TITLE
JobWrapper should delegate #expiration to actual job class in ServerMiddleware#call

### ISSUE THREAD

**Issue by lastobelus** [utgarda/sidekiq-status#111]
A third party framework that passes very large hashes in args is now killing my Redis instance.

In the meantime, I need long-lived status (1 day) for my sidekiq workers where I am using sidekiq-status **intentionally**.

**Comment by lastobelus** [comment]
note: I am **NOT** doing this:

```
# app/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
  include Sidekiq::Status::Worker
end
```

yet, sidekiq status is logging the args of ActiveJob workers, with `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper` as the `Worker/JID`, and always with status `Working`, though the jobs complete without failure.

**Comment by lastobelus** [comment]
Hmmm, this is actually happening on `sidekiq-status 0.6` -- I had assumed it was a symptom of the 0.7 update, but actually was happening prior to that. 

After updating to sidekiq 5.x & sidekiq-status 0.7, status of ActiveJobs is still being logged, despite the fact that I have not included `Sidekiq::Status::Worker` in `ApplicationJob`.

On my production app, trying to clear out the offending set of logged jobs by setting `Sidekiq::Status::ServerMiddleware, expiration: 1`  failed -- sidekiq status panel now times out.

**Comment by lastobelus** [comment]
My production mystery deepens. Redis has 7000+  sidekiq:status:* keys, though the jobpanel shows less than 100 entries.

**Comment by lastobelus** [comment]
I tried updating to 0.7.0, and including `include Sidekiq::Status::Worker` in `ApplicationJob` and defining an `expiration` method, but sidekiq:status still saves activejob args for the global expiration time set on the middleware.

**Comment by lastobelus** [comment]
I managed to get a separate expiration time for ActiveJob jobs with the following initializer:

```ruby
module ActiveJob
  module QueueAdapters
    class SidekiqAdapter
      class JobWrapper
        def expiration
          @expiration ||= 10
        end
      end
    end
  end
end
```

**Comment by lastobelus** [comment]
I think if sidekiq-status is going to do anything with activejobs, some sort of control over it needs to be made available to the user of the gem.

**Comment by pramodshinde** [comment]
If adding/removing `include Sidekiq::Status::Worker` line into active job class not controlling the enable/disable then it's a bug for sure. I will try to reproduce this at my end as per your illustration.

Out of curiosity How the following code setting separate expiration for third party jobs only? or You are trying to reduce expiration time for all active jobs?

```
module ActiveJob
  module QueueAdapters
    class SidekiqAdapter
      class JobWrapper
        def expiration
          @expiration ||= 10
        end
      end
    end
  end
end
```

**Comment by lastobelus** [comment]
For the time-being, I want to reduce expiration time for all activejobs -- my only use of activejobs is via a third-party framework. All the workers I write are direct Sidekiq workers.

It's going to be a slightly tricky bug to resolve -- in the current flow activejob hasn't actually deserialized the job yet when you're checking expiration.

**Comment by kenaniah** [comment]
Look like we might have to hack `ActiveJob::Core#deserialization`  or `JobWrapper` or `Sidekiq::Status::SeverMiddleware` or some combination of the aforementioned to ensure that expiration is properly consulted. At worst, we may need to provide our own `:sidekiq-status` job adapter which would delegate the `#expiration` call to the actual job class that was wrapped.

**Comment by kenaniah** [comment]
@lastobelus could I ask you to take a look at PR #113 and see if that solves your use case?

**Comment by lastobelus** [comment]
@kenaniah Thanks! it certainly looks as though it will -- I'll deploy first chance I get and let you know if I have any issues.
