### ISSUE TITLE
Communicate less with Redis

### ISSUE THREAD

**Issue by JanStevens** [utgarda/sidekiq-status#116]
We noticed that a lot of additional calls are made for getting back the status and percentage done.

Looking at the following code a total of 3 redis calls are needed to calculate the pct_complete, if you then also need the status thats an additional call.

```ruby
 def pct_complete(job_id)
      ((at(job_id) / total(job_id).to_f) * 100 ).to_i if total(job_id).to_f > 0
 end
```

We applied the following monkey patch that reduces the amount of redis calls needed by caching total in the worker instance.

```ruby
# Monkey patch Sidekiq::Status::Worker so we already calculate the
# percentage completed and cache the total

module ImprovedSidekiqStatusWorker
  # Sets current task progress and calculate the pct_complete
  # @param Fixnum number of tasks done
  # @param String optional message
  # @return [String]
  def at(num, message = nil)
    @_total = 100 if @_total.nil?
    pct_complete = ((num / @_total.to_f) * 100 ).to_i
    store(at: num, total: @_total, pct_complete: pct_complete, message: message)
  end

  # Sets total number of tasks
  # @param Fixnum total number of tasks
  # @return [String]
  def total(num)
    @_total = num
    store(total: num)
  end
end

Sidekiq::Status::Worker.prepend(ImprovedSidekiqStatusWorker)
```
This allows us to retrieve all information with one `Sidekiq::Status.get_all` call to redis instead of 4 calls. I think additional performance can be gained if `Sidekiq::Status` would use `get_all` for all it's public methods (instead of selectively extracting parts of the stored hash).

Let me know if you are interested in a PR that addresses these issues

**Comment by kenaniah** [comment]
Definitely interested. Performance improvements are always welcome, and we would love to see a PR for this.

**Comment by kenaniah** [comment]
@JanStevens could I ask you test your environment against my PR? 

I'm hesitant to cache against `#get_all` as values may be out of date in between invocations, but what's in the PR should take care of the major pain points.
