### ISSUE TITLE
uninitialized constant Sidekiq::Actor::Celluloid (NameError)

### ISSUE THREAD

**Issue by lfarcy** [utgarda/sidekiq-status#120]
I'm trying to upgrade my codebase with the latest sidekiq-status version (v0.8.0). I use a rather old Sidekiq, v3.5.4.

When sidekiq-status is to be loaded, by bundler for instance, it fails b/c it does not find the ``` Sidekiq::Actor::Celluloid``` module.

It's a bit funny b/c I'm responsible for the bug... By introducing the ```:retrying``` state into sidekiq-status, I added a dependency over ```Celluloid```. Of course, it was not intended.

Here's what's happening

1. The sidekiq-status server middleware needs to know the default max number of retry attempts from Sidekiq itself
2. For Sidekiq < v5.x, it's defined as a constant on the ```Sidekiq::Middleware::Server::RetryJobs``` middleware module.
3. This module has a dependency on ```Sidekiq::Scheduled``` and, hence, requires 'sidekiq/scheduled'. This is very not clear to me why this module is needed by the ```RetryJobs``` middleware. But, since it's Sidekiq codebase, there's nothing I can do about that.
4. The ```Sidekiq::Scheduled``` module depends on ```Sidekiq::Actor``` which, itself, references the ```Celluloid``` module when included into another module. But it does not require 'celluloid' b/c Sidekiq has a special way of loading Celluloid to avoid conflicts with daemonization.

It's similar to an [issue](https://github.com/brainopia/sidekiq-limit_fetch/pull/5) solved for ```sidekiq-limit_fetch```.

I don't find a "clean" solution to this problem

- I don't see how I can apply the same technique used by ```sidekiq-limit_fetch```.
- I can hardcode the default max number of retry attempts for Sidekiq < v5.x in sidekiq-status codebase itself to 25, hence getting rid of the problematic dependency.

Any help/opinion/suggestion welcome. I feel like I won't be the only one to get this error.

**Comment by kenaniah** [comment]
Should now be fixed in a52827b65004ae119424ce9a282a93b177100bfc

**Comment by kenaniah** [comment]
Please try v0.8.1 and let me know if you're still having issues. Thanks!

**Comment by lfarcy** [comment]
@kenaniah So you decided to go with the 'hardcoding' option. Which I'm totally fine with. Very pragmatic indeed.

But, I did not ask for a commit :) I intended to make the contribution by myself. Thx for the time you took for this 👍 

I'm going to test v0.8.1 today and confirm it solves this issue.
