### ISSUE TITLE
Hide Completed Jobs

### ISSUE THREAD

**Issue by scottrobertson** [utgarda/sidekiq-status#123]
Hey

Is there a way to hide completed jobs from the status page? We have used our own fork of this gem for a few years, and i am now looking to use upstream, but this is a big issue as we have 5k pages of completed jobs, and it's very slow to load. It also doesn't allow us to keep track of what jobs are currently running very well.

**Comment by kenaniah** [comment]
@scottrobertson I'm very much open to a PR to filter out completed jobs. Would you be interested in opening one?

Later versions of this gem also allow you to customize the amount of time completed jobs hang around, which may help alleviate some of that 5K page backlog.

**Comment by scottrobertson** [comment]
@kenaniah we do about 5 million jobs a day, so that would need to be set very low :D 

I will look into this if i get some time, yeah. For now, i have just had to go back to using our fork.

**Comment by scottrobertson** [comment]
@kenaniah can you think of a nice way to implement this? The version we have seems to not show completed jobs at all (it's old) so i am not sure what the UX should be like with the most recent versions of sidekiq-status.
