### ISSUE TITLE
Sort by enqueued_at

### ISSUE THREAD

**Issue by scottrobertson** [utgarda/sidekiq-status#124]
Hey

We process around 5 million jobs per day, so our sidekiq is very very busy. One thing we have found is that by sorting the /statuses endpoint by `enqueued_at` it keeps things much more readable and clean on that page, especially when you have longer running jobs. It stops the jobs from just jumping around all over the place on every poll.

Just figured I would point it out, as it may benefit others if it were available to them.

**Comment by kenaniah** [comment]
@scottrobertson Sounds like a great idea. Would love to see a PR for this, especially if you've already solved it 😉

**Comment by scottrobertson** [comment]
@kenaniah can you think of a way to get the enqueued_at. Looking at the code, it's all very very different to our fork, and i am not sure it's available anymore?
