### ISSUE TITLE
UI customisation?

### ISSUE THREAD

**Issue by duncan-bayne** [utgarda/sidekiq-status#126]
Currently, I am customising our sidekiq UI by placing custom `.erb` files in `app/views/sidekiq`.

Is there a similar method by which I can customise sidekiq-status UI?  I've found that it seems to disregard files in either `app/views/sidekiq` or `app/views/sidekiq-status`.

**Comment by kenaniah** [comment]
I would imagine this would be possible if you were to redefine the `Sidekiq::Status::Web::VIEW_PATH` constant or by overriding the `#sidekiq_status_template` helper.
