### ISSUE TITLE
Misleading docs or bug?

### ISSUE THREAD

**Issue by bjedrocha** [utgarda/sidekiq-status#127]
Hi there,

According to the README

> As of version 0.8.0, only jobs that include Sidekiq::Status::Worker will have their statuses tracked.

This is incorrect as [any job that throws an exception will have their status tracked](https://github.com/utgarda/sidekiq-status/blob/47ab55abf4ab0053cde6abc86c702ae9557edd72/lib/sidekiq-status/server_middleware.rb#L57-L67).

This seems like a bug to me but I wanted to ask before opening a PR. If, however, this is in fact desired functionality, would you be interested in a PR that made this configurable?

Cheers

**Comment by kenaniah** [comment]
That's a great question, and you are indeed correct in your assertion. I think the most intuitive thing to do in this case would be to match what the README advertises, so let's call it a bug. 

If you're interested in opening a PR with a test to cover this scenario, I'd be happy to merge and release a new version once passed.
