### ISSUE TITLE
Use of Module.const_get() introduces a dependency on Ruby 2.*

### ISSUE THREAD

**Issue by benissimo** [utgarda/sidekiq-status#130]
Prior to 2.*, Ruby's `Module.const_get` doesn't resolve namespaced classes.
Version 0.8.0 of sidekiq-status introduces the use of `Module.const_get`, which causes Sidekiq::Status to trigger NameError when passed a namespaced class's job.

I worked around this by patching `Sidekiq::Status::Module.const_get` (since `Module.const_get` is called without a `::` prefix, it was easy to patch it locally).

```
require 'sidekiq-status'

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.0.0')
  raise "Remove the Sidekiq::Status patch below. Module.const_get() in Ruby 2+ handles namespaced class name lookups"
end
module Sidekiq::Status
  class ClientMiddleware
    module Module
      class << self
        def const_get_with_constantize(name, inherit = true)
          if inherit && name.respond_to?(:constantize)
            name.constantize
          else
            const_get_without_constantize name, inherit
          end
        end

        alias_method_chain :const_get, :constantize
      end
    end
  end
end

module Sidekiq::Status
  class ServerMiddleware
    module Module
      class << self
        def const_get_with_constantize(name, inherit = true)
          if inherit && name.respond_to?(:constantize)
            name.constantize
          else
            const_get_without_constantize name, inherit
          end
        end

        alias_method_chain :const_get, :constantize
      end
    end
  end
end
```

^ I relied on `String#constantize`, which is mixed in to `String` by `ActiveSupport`. That's fine for my use case (a Rails app, that already relies on ActiveSupport) but not a good general fix. I'm just listing this workaround in case others happen to be in the same situation (Ruby < 2; app that uses ActiveSupport).

**Comment by kenaniah** [comment]
Hi @benissimo. Thanks for tracking this down and posting a workaround for anyone else who may still be running a 1.9.x version of Ruby. 

Ruby 1.9.x has been end-of-life since 2015-02-23, and I'll close this issue accordingly as this version will not be supported directly.
