### ISSUE TITLE
Remove button leads to a 404 Not Found

### ISSUE THREAD

**Issue by DannyBen** [utgarda/sidekiq-status#145]
Pressing the Remove button of completed jobs inside the Statuses tab leads to a 404.

This is the HTML element of the generated button.

```html
<div class="actions">
  <form action="statuses" method="post">
    <input type="hidden" name="jid" value="a33...35b">
    <input type="hidden" name="authenticity_token" value="PHx...U8=">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" class="btn btn-danger btn-xs" value="Remove">
  </form>
</div>
```

I am mounting the dashboard using `Rack::URLMap` - but it is mounted as the root and using current versions of everything.

**Comment by DannyBen** [comment]
Additional info: Clicking the button sends a POST request and not a DELETE request, as is hinted by the `_method` hidden field.

Any chance of someone more familiar with the project taking a look at it?

**Comment by makotoshimoda** [comment]
> Additional info: Clicking the button sends a POST request and not a DELETE request, as is hinted by the `_method` hidden field.
> 
> Any chance of someone more familiar with the project taking a look at it?

Hi, @DannyBen...
I had the same problem and you need to configure your middleware to make it work.

>>Rack::MethodOverride allows the method to be overridden if params[:_method] is set. This is the middleware which supports the PATCH, PUT, and DELETE HTTP method types.

I hope this can help you with your problem.

**Comment by DannyBen** [comment]
Thanks a lot @makotoshimoda, I appreciate you taking the time to post this.

Since I am using it outside of a Rails setup, I didn't have this middleware enabled.

Adding `use Rack::MethodOverride` indeed fixed it.
