### ISSUE TITLE
Finishing a worker at < total results status = completed and < 100% progress

### ISSUE THREAD

**Issue by github0013** [utgarda/sidekiq-status#148]
I just started using your gem, and I was thinking it would be nice if the progress automatically got 100% when completed.

As of version 1.1.2, you need to make sure you set `at 100` at the end of your perform, to make sure you have 100% progress when it's done.

```rb
  def perform(*args)
    total 100
    at 5, "just started"
    sleep 3
    at 90, "almost"
    sleep 6
    at 90, "done"
  ensure
    at 100 # unless otherwise you get something like the image below
  end
```

![_DEVELOPMENT__Sidekiq](https://user-images.githubusercontent.com/809378/56258223-c6d5a180-6109-11e9-82a6-7852889c02f5.png)

Just a quick look, I think if you add these 2 lines before https://github.com/utgarda/sidekiq-status/blob/v1.1.2/lib/sidekiq-status/server_middleware.rb#L51, it will work?

```rb
worker.total(100)
worker.at(100)
```

Let me know your comment.
Thanks

**Comment by kenaniah** [comment]
After considering, I don't believe this to be an issue with the gem, but rather with how it's used. A progress bar that is not complete is a very good indicator of a buggy job.
