### ISSUE TITLE
Deleting the job from the UI doesn't update the status

### ISSUE THREAD

**Issue by Geesu** [utgarda/sidekiq-status#16]
http://cl.ly/image/0L0H0w2y1o3x

Basically I delete the item from a queue within the UI, and then after I queue the status it is still listed as :queued

[6] pry(main)> status = Sidekiq::Status::status('4f5d19bcf07013ecfbc38486')
=> :queued

**Comment by gregblass** [comment]
Hey @Geesu - I noticed this and was a little concerned. How did you go about handling this? I'm not sure if we'll ever delete jobs from the web UI - but if we did, the status would be out of sync?

**Comment by Geesu** [comment]
> Hey @Geesu - I noticed this and was a little concerned. How did you go about handling this? I'm not sure if we'll ever delete jobs from the web UI - but if we did, the status would be out of sync?

I have no idea :( This was so long ago.
