### ISSUE TITLE
Call Sidekiq::Status.cancel with Ruby 3.0.0

### ISSUE THREAD

**Issue by durcak** [utgarda/sidekiq-status#161]
I have upgraded ruby version to 3.0.0 and now I have problems with **Sidekiq::Status.cancel** method.

 When I call `Sidekiq::Status.cancel(job_id)` it fails with error `ArgumentError:
       wrong number of arguments (given 4, expected 3)`, which comes from `.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/redis-4.2.5/lib/redis.rb:1961:in 'zrangebyscore'`
       
  I think, it can be fixed with updating this method
  
  ```
  # Gets the batch of scheduled jobs based on input options
  # Uses Redis zrangebyscore for log(n) search, if unix-time is provided
  # @param [Hash] options, options hash containing (REQUIRED) keys:
  #  -  conn: Redis connection
  #  -  start: start score (i.e. -inf or a unix timestamp)
  #  -  end: end score (i.e. +inf or a unix timestamp)
  #  -  offset: current progress through (all) jobs (e.g.: 100 if you want jobs from 100 to BATCH_LIMIT)
  def schedule_batch(options)
    options[:conn].zrangebyscore "schedule", options[:start], options[:end], {limit: [options[:offset], BATCH_LIMIT]}
  end
```

to

```
  def schedule_batch(options)
    options[:conn].zrangebyscore "schedule", options[:start], options[:end], **{limit: [options[:offset], BATCH_LIMIT]}
  end
```

Can you add support for ruby 3.0.0?

Thanks.

**Comment by kenaniah** [comment]
Hi @durcak, support for Ruby 3 has been added in version 2.0.0, which is now maintained at https://github.com/kenaniah/sidekiq-status.
