### ISSUE TITLE
Sidekiq::Job renamed to Sidekiq::JobRecord

### ISSUE THREAD

**Issue by tblais1224** [utgarda/sidekiq-status#166]
https://github.com/utgarda/sidekiq-status/blob/96fbe56b6d4cebc7cb6ae44f42da54b347b104dd/lib/sidekiq-status/client_middleware.rb#L37
https://github.com/utgarda/sidekiq-status/blob/96fbe56b6d4cebc7cb6ae44f42da54b347b104dd/lib/sidekiq-status/client_middleware.rb#L48

Please rename the Job class call here to JobRecord to avoid the name error. Here is the change in sidekiq https://github.com/mperham/sidekiq/commit/f1b24da9c225a5512120514d32a5348760e92f3a

**Comment by kenaniah** [comment]
This repo has been effectively archived (but I don't have the ability to actually archive it), and this has been addressed in the later versions of the gem. See README for more info.
