### ISSUE TITLE
inline::testing update

### ISSUE THREAD

**Issue by washu** [utgarda/sidekiq-status#18]
module Sidekiq
  module Status
    class << self
      def status(jid)
        :complete
      end
      def message(jid)
        ""
      end
    end
    module Storage
      def store_for_id(id, status_updates, expiration = nil)
      end
      def read_field_for_id(id, field)
      end
    end
  end
end

Allows at command to be used during testing .. goes no where but with inline blocks and no redis code in test cases can still be executed.

**Comment by dmitry** [comment]
@washu are you still using this extension?

**Comment by washu** [comment]
not anymore

**Comment by dmitry** [comment]
@washu have you found alternative?
