### ISSUE TITLE
Jobs status should be stored in a container

### ISSUE THREAD

**Issue by Silex** [utgarda/sidekiq-status#23]
When I look at redis with `redis-browser`, I see that job status are stored directly at root with the jid as key... I think it makes more sense to put them in some `sidekiq:status:` container.

The current way makes browsing redis a pain.

**Comment by apalancat** [comment]
I think this would be really useful, but certainly not backwards-compatible.
I assume since this project hasn't reached 1.0 people are aware that breaking changes can occur.
I believe that in order to be able to do more interesting things with statuses this change needs to happen.

**Comment by pramodshinde** [comment]
@utgarda - Why this issue and #53 still hanging around here, Can you close both I can see fix in PR #56 ?

**Comment by utgarda** [comment]
Fixed in 0d2d7f8bb94b6a930619c2ddf537fd15291be93e
