### ISSUE TITLE
Sidekiq::Status::status always returns nil

### ISSUE THREAD

**Issue by ericpeters0n** [utgarda/sidekiq-status#37]
I'm not seeing any status (or other data) for jobs created using this kind of call:
```
job_id = MyWorker.perform_async(arg1, arg2) # this successfully generates a job_id
# time passes, some work is done...
pct_complete = Sidekiq::Status::pct_complete job_id # always Nan
completed = Sidekiq::Status::complete? job_id # always false
```

Here's my worker, which does it's work successfully:
```
class MyWorker
  include Sidekiq::Worker
  include Sidekiq::Status::Worker
  
  def perform(arg1, arg2)
    begin
      array_of_people = magically_get_array_of_people # ...

      total array_of_people.size
      at 0, "Starting..."

      array_of_people.each_with_index do |f, index|
        at index, "Working..."
      end
    rescue => ex
      logger.warn ex
    end
  end
end
```

Sidekiq::Status always returns Nan, nil, etc. for all doc'd commands.  The gem doesn't appear to actually receiving the updates generated in the Worker. Seems like it might be a config issue... so here's my config/initializers/Sidekiq.rb:
```
require 'sidekiq'
require 'sidekiq-status'

Sidekiq.configure_client do |config|
  config.redis = { :url => ENV["REDISTOGO_URL"], :size => 1 }
  # sidekiq-status
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
  #
end

Sidekiq.configure_server do |config|
  config.redis = { :url => ENV["REDISTOGO_URL"], :size => 2 }
  # sidekiq-status
  config.server_middleware do |chain|
    chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
  end
  config.client_middleware do |chain|
    chain.add Sidekiq::Status::ClientMiddleware
  end
  #
end
```
Any hints on a likely culprit here?

**Comment by pramodshinde** [comment]
@ericpeters0n & @jakegavin  can you confirm if this has been resolved?

**Comment by ericpeters0n** [comment]
I was obliged to work around this issue (~1yr ago). 

Will see if there's a simple way to retest, but no, there was no resolution.

**Comment by jakegavin** [comment]
I'm no longer using this gem but if I recall correctly, I wasn't having any issues with it. My switch to a different solution was the result of a cleaner approach to the business problem, nothing specifically related to this gem.

Thanks for the work you put into maintaining it!

**Comment by pramodshinde** [comment]
:+1:  Great!
