### ISSUE TITLE
Returning hashes from worker is troublesome

### ISSUE THREAD

**Issue by sjmog** [utgarda/sidekiq-status#48]
Say I compile an array of hashes in the worker, and set them to be retrieved using a key like this:

    @array_of_hashes = [{"key" => "value"}, {"key2" => "value2"}]
    store keys_and_values: @array_of_hashes.to_s
    keys_and_values = retrieve :keys_and_values

I can now access keys_and_values in a controller like this:

    @data = Sidekiq::Status::get_all job_id # job_id is the ID of the job which has been stored somewhere

And render it to the browser as JSON like this:

    render json: @data

The data comes out groovily, except for all the horrible key-value stuff, which comes out like this:

    keys_and_values: "[{"key" => "value"}, {"key2" => "value2"}]"

And I can't parse that to valid JSON because of all the quotations.

But if I try to return array data without calling `to_s` on it first, I'm not returning strings and Sidekiq can't handle it.

How oh how could I resolve this problem?

**Comment by sjmog** [comment]
Using `to_json` instead of `to_s` still results in horrible things:

    keys_and_values: "[{"key": "value"}, {"key2": "value2"}]"

**Comment by utgarda** [comment]
And what would be your desired behaviour? So far looks legit to me, what you encode as json, same thing you get back when you parse it:
```ruby
[etsvigun@jotunheim ~]$ irb
2.1.5 :001 > require 'json'
 => true 
2.1.5 :002 > @array_of_hashes = [{"key" => "value"}, {"key2" => "value2"}]
 => [{"key"=>"value"}, {"key2"=>"value2"}] 
2.1.5 :003 > jsn = @array_of_hashes.to_json
 => "[{\"key\":\"value\"},{\"key2\":\"value2\"}]" 
2.1.5 :004 > parsed = JSON(jsn)
 => [{"key"=>"value"}, {"key2"=>"value2"}] 
2.1.5 :005 > parsed == @array_of_hashes
 => true 
```

**Comment by sjmog** [comment]
Thanks: I think I done goofed the transfer to JSON. It wasn't including the escapes around the double quotes.
