### ISSUE TITLE
Simplify unscheduling

### ISSUE THREAD

**Issue by mrsimo** [utgarda/sidekiq-status#51]
Hi there,

I'd like to open a PR for this, but I wanted to double check with you first if you think it makes sense.

We use [`zrangebyscore`](https://github.com/utgarda/sidekiq-status/blob/9b36f4fd6985a2cd8232d310890326a246a1272f/lib/sidekiq-status/storage.rb#L84) to look for the job in the `schedule` sorted set. That operation has a complexity of:

> `O(log(N)+M)` with N being the number of elements in the sorted set and M the number of elements being returned. If M is constant (e.g. always asking for the first 10 elements with LIMIT), you can consider it `O(log(N))`.

After that weuse [`zrem`](http://redis.io/commands/zrem) with a complexity of:

> `O(M*log(N))` with N being the number of elements in the sorted set and M the number of elements to be removed.

Since we're removing 1 element, it becomes `O(log(N))`.

We look for the job in the `schedule` set to know if we can remove it, but `zrem` returns the number of removed elements, so we could use that to decide if the element was there and just delete it. Is that right?

I have a use case where we have quite a few scheduled jobs that I need to unschedule sometimes, and if I didn't need to keep track of the timestamp it would simplify things a bit.

**Comment by mrsimo** [comment]
I started to implement this and quickly realized that the `schedule` set has serialized jobs, so the theory is impossible. Sorry for the trouble!

**Comment by utgarda** [comment]
Thanks for your concern :)
