### ISSUE TITLE
Not Worked With Rails 4 ActiveJob?

### ISSUE THREAD

**Issue by zw963** [utgarda/sidekiq-status#52]
## rails initializer

``` ruby
  require 'sidekiq-status'

  # 设定 sidekiq-status 中间件.
  Sidekiq.configure_client do |config|
    config.client_middleware do |chain|
      chain.add Sidekiq::Status::ClientMiddleware
    end
  end

  Sidekiq.configure_server do |config|
    config.server_middleware do |chain|
      chain.add Sidekiq::Status::ServerMiddleware, expiration: 30.minutes # default
    end
    config.client_middleware do |chain|
      chain.add Sidekiq::Status::ClientMiddleware
    end
  end
```
## job define:

``` ruby
class Order::RemitJob < ActiveJob::Base
  include Sidekiq::Worker

  def perform(order)
    order.transition_to! 'finished'
  end
end
```
## model define

``` ruby
  def remit_job
    job = RemitJob.set(wait: Rails.application.config.x.buyer_auto_receive_delay.hours).perform_later(self)
    status = Sidekiq::Status::status(job.job_id)   # => here always return nil.
  end
```

I can confirm Sidekiq is started and worked for me, But I can't get it status with this gem.

**Comment by jjhahnjj** [comment]
I was running into the same issue where the jobs are running fine, and I can see them in the /statuses but I would not be able to retrieve the status. They always returned an empty object {}.
 
After I changed the activejob to a pure sidekiq job, status started working...

**Comment by esbanarango** [comment]
:+1:

**Comment by arnkorty** [comment]
I found the activejob return jobid and sidekiq jobid is different. Do you know how to get the real job id with  activejob? thanks.
<img width="952" alt="47230d7b-cb9c-4e5c-ac2d-5262e8209d5e" src="https://cloud.githubusercontent.com/assets/2126904/9840396/139bd9a8-5ac4-11e5-84bd-75a321ed26d2.png">
<img width="857" alt="ec23d641-b51b-40d5-9b82-402df1458f85" src="https://cloud.githubusercontent.com/assets/2126904/9840397/17dd1ef0-5ac4-11e5-80e3-8e7fb7c2ac08.png">

**Comment by zw963** [comment]
@arnkorty , setting it in your's  ActiveJob::Base subclass.

e.g.

```ruby
class Order::DelayedActionJob < ActiveJob::Base
  attr_accessor :jid
  around_enqueue do |job, block|
    job.jid = block.call
  end

  def perform(order, permitted_states, target_state, description)
        # do something
  end
end

```

**Comment by cerdiogenes** [comment]
@arnkorty you can also use the old syntax, it's return the sidekiq job id: `UserMailer.delay.mail_method`

**Comment by dmitry** [comment]
Is there are still a problem with latest ActiveJob?

**Comment by rept** [comment]
Should this work when I do a deliver_later ?  I don't get any status when I mail like that.

**Comment by nfedyashev** [comment]
@zw963 thank you so much for posting this workaround!

**Comment by kenaniah** [comment]
I recently added support for ActiveJob in https://github.com/utgarda/sidekiq-status/commit/fcd820e8870a5ced9fd12c7e9db2690a2ec25e72, which will show up in `0.7.0` when it's released.
