### ISSUE TITLE
Namespace redis keys

### ISSUE THREAD

**Issue by Valve** [utgarda/sidekiq-status#53]
Currently this gem adds top-level keys, for example 
`
"hmset" "a3621311f0aef8626935b249" "update_time" "1428675833" "status" "queued"
`

they pollute the redis keyspace. I suggest to namespace them, like 
'sidekiq-status:a3621311f0aef8626935b249'

**Comment by pdf** [comment]
Dupe of #23

**Comment by utgarda** [comment]
Fixed in 0d2d7f8bb94b6a930619c2ddf537fd15291be93e
