### ISSUE TITLE
:interrupted status

### ISSUE THREAD

**Issue by dmkl** [utgarda/sidekiq-status#54]
If I reboot my worker when it runs `Sidekiq::Status.status` always returns `:working`, although the job is not running anymore. Is there a way to figure out that my job was interrupted?

**Comment by niuxiufeng** [comment]
I have the same problem,
after this
kill -TTIN ...
the job status still is working.

**Comment by shyamster** [comment]
I have the same issue as well. Would be great to know what the job has been interrupted

**Comment by pramodshinde** [comment]
@utgarda - Expecting you to close this after gem update :)

**Comment by pramodshinde** [comment]
Fixed in #67
