### ISSUE TITLE
Testing inline! does not clear redis status

### ISSUE THREAD

**Issue by dcdieci** [utgarda/sidekiq-status#58]
Hi,

I am running sidekiq status in inline mode, since I want to execute the worker right away.
the worker runs fine, but the status in redis remains in queue forever.

in development.rb I have.
require 'sidekiq/testing'
  Sidekiq::Testing.inline!

So the question is how can I get the status when running inline?

**Comment by dmitry** [comment]
Have use required status testing?

https://github.com/utgarda/sidekiq-status#testing

**Comment by kenaniah** [comment]
When running in inline mode (via `require 'sidekiq-status/testing/inline`), the status returned would always be `:complete`, and there's currently no way to get other statuses in this mode.

I would recommend allowing jobs to be pushed to redis during testing via:

```ruby
require 'sidekiq/testing'
Sidekiq::Testing.disable! # allows jobs to be pushed to redis. Call #enable! to reverse
```

You would then be able to retrieve statuses normally as you would expect, but note this causes Sidekiq to queue and execute the job normally as well.

**Comment by kWhittington** [comment]
So, there's no way to actually use `Sidekiq` in test mode w/o a setup `Redis` queue if you're using `sidekiq-status`?

You either live w/false positives or actually set up `Redis`?
