### ISSUE TITLE
Wrong Gem Version when Pull

### ISSUE THREAD

**Issue by tfluehmann** [utgarda/sidekiq-status#60]
Hi, 
we would like to use sidekiq-status in our environment, at the moment when we pull we don't get the newest code without the limitation of sidekiq gem.
Could you please tag and publish a new version?
![sidekiq-status](https://cloud.githubusercontent.com/assets/5341776/8448671/7ff5b8c4-1fca-11e5-80ab-ceb03d951354.PNG)

Thanks

**Comment by akalyaev** [comment]
+1

**Comment by guyisra** [comment]
+1

**Comment by utgarda** [comment]
Done. Guys, as you probably noticed, this project needs a new maintainer, preferrably one that uses it in everyday work. I moved quite far from active Ruby development, so now I'm unfit for the task. Let me know if you're interested in supporting it. If I find someone willing and worthy, I'll just transfer the repo and gem ownership.
