### ISSUE TITLE
Compatibility with :jid returned in testing enviroment

### ISSUE THREAD

**Issue by jdanielnd** [utgarda/sidekiq-status#7]
The following commit changes the `client_push` method in testing environment so as it returns an job id.

https://github.com/mperham/sidekiq/commit/8dd3660646a90f41ef2cfcac485119260e9c9e64

Would be nice if `sidekiq-status` could retrieve jobs from the testing environment as well, instead of looking into Redis.

**Comment by kenaniah** [comment]
Pull requests are welcome! In the mean time, I'm going to close this as a feature that the maintenance team is not planning on building as part of our roadmap.
