### ISSUE TITLE
Why Different format of Arguments shown?

### ISSUE THREAD

**Issue by nazarhussain** [utgarda/sidekiq-status#79]
Hello, 

This gem is very useful for us. Thanks for developing it. 

I am facing a problem that arguments format in normal sidekiq listing and status listing is totally different. For status listing arguments is not in readable format. Check the images below: 

First image is listing of your plugin. Second image is listing of standard sidekiq. You will notice how easy and readable is the standard sidekiq listing. In status listing we can't ready which job with which arguments was run. 

Please suggest how to fix it. 

![arguemnts2](https://cloud.githubusercontent.com/assets/112468/12491798/bf94cdb0-c09e-11e5-9061-369f7d4a606d.png)

![arguments2](https://cloud.githubusercontent.com/assets/112468/12491807/c8868724-c09e-11e5-926a-469b0205bc92.png)

**Comment by pramodshinde** [comment]
This is fixed for `'sidekiq'  '>= 2.7'`, But for `'sidekiq' '~> 2.7'` arguments will not be displayed formatted as ~> 2.7 itself displays arguments as un-formatted.
