### ISSUE TITLE
Don't crash when redis is down?

### ISSUE THREAD

**Issue by benoittgt** [utgarda/sidekiq-status#80]
Hello

First thanks a lot for the gem. I would like to know if it will be possible to avoid crashing when redis is down. If redis is down and sidekiq status is installed it crash at the first call (because of the middleware settings). I gave a quick look without founding the proper answer to patch it. 

Is making check [after method](https://github.com/utgarda/sidekiq-status/blob/33ae35718d4e553483e42859f4f7b05d6bc8f5a0/lib/sidekiq-status/client_middleware.rb#L19-L26) `call` of redis connection will be a good idea? It's seems quite dirty to my point.

The problem is yesterday our redis was buggy and the server crashed a lot because of Sidekiq-Status trying to connect to redis and crashing. 😞 

Thanks

**Comment by lin63** [comment]
The same problem. but I found [this](https://github.com/mperham/sidekiq/issues/1662) which replayed by @lastobelus . It's a good idea to fix it.  At the master version, you need add a patch like bellow:
```
module Sidekiq::Status
  module Testing
    class << self
      def statii(jid)
        @statii ||= {}
        @statii[jid] ||= []
      end

      def push_status(jid, status)
        statii(jid) << status
      end

      def fake!
        @fake = true
      end
      def fake?
        @fake
      end
      def disable!
        @fake = false
        @statii = nil
      end

      def clear!
        disable!
      end
    end
  end

  module Storage
    def store_for_id(id, status_updates, expiration = nil, redis_pool = nil)
      if Sidekiq::Status::Testing.fake?
        Sidekiq::Status::Testing.push_status(id, status_updates)
      else
        super
      end
    end
  end
end    
```

**Comment by dmitry** [comment]
I checked other sidekiq extensions, and they are doing the same way. Don't think it's the sidekiq-status issue.

**Comment by benoittgt** [comment]
Ok. No problem. Issue can be close if you want.

**Comment by dmitry** [comment]
@benoittgt but how it should work from your perspective?
@utgarda /cc what do you think?

**Comment by benoittgt** [comment]
To be honest I removed sidekiq-status and write my own module. I was not using lot's of feature of sidekiq status so it was not hard to do what I wanted. ;)

**Comment by dmitry** [comment]
@benoittgt but did you had any redis connection issues since you wrote your own middleware, so it resolved this problem?

**Comment by benoittgt** [comment]
No. I just rely on Sidekiq API. I'm sorry it's quite old, I fail to remember everything but I don't have any more issue. 😃

**Comment by pramodshinde** [comment]
I think this is in inline with `sidekiq`, Please feel free to open it again if anyone have better ideas, closing now.
