### ISSUE TITLE
v0.6.0 appears in rubygems; no such tag here; latest is v0.5.4

### ISSUE THREAD

**Issue by baburdick** [utgarda/sidekiq-status#82]
[Rubygems shows](https://rubygems.org/gems/sidekiq-status) v0.6.0 was released on December 27, 2015.

And the diff looks non-malicious. It pretty much corresponds with this: https://github.com/utgarda/sidekiq-status/compare/v0.5.4...d92fca48747fe25eac0821e955145dbf52327fa7

So it looks legitimate (making this a very minor issue). But it could use a v0.6.0 tag.

**Comment by chamnap** [comment]
👍

**Comment by pramodshinde** [comment]
Added new release tag with [v0.6.0](https://github.com/utgarda/sidekiq-status/releases/tag/v0.6.0)
