### ISSUE TITLE
job status unchanged even after deleting job from the queue

### ISSUE THREAD

**Issue by sushantbajra** [utgarda/sidekiq-status#90]
```
queue = Sidekiq::Queue.new
    queue.each do |job|
      if job.jid ==  session[:job_id]
         job_removed=job.delete

      end
    end
```
Even after deleting the job from the queue, running `ap Sidekiq::Status::status(session[:job_id])` keeps giving me `:queued`. I have to run `Sidekiq.redis { |conn| conn.flushdb }` to clear all the jobs from the redis. Any way to solve this issue?

**Comment by pramodshinde** [comment]
Currently there is no API for deleting job status by job_id only **scheduled** jobs can be deleted like `Sidekiq::Status.cancel scheduled_job_id`. 

But for now you can patch like following 
```
conn = Sidekiq.redis { |conn| conn }
queue = Sidekiq::Queue.new
queue.each do |job|
  if job.jid ==  session[:job_id]
    conn.del "sidekiq:status:#{job.jid}"
    job_removed=job.delete
  end
end
```
I know proposed way is not an ideal way to achieve this I will add an API very soon, but this should work for you.
