### ISSUE TITLE
Fix build for sidekiq '2.7'

### ISSUE THREAD

**Issue by pramodshinde** [utgarda/sidekiq-status#93]
Fix current master [build](https://travis-ci.org/utgarda/sidekiq-status/builds/165589144) as 
`require 'celluloid'` replaced with `require 'celluloid/current'` (supported in celluloid ~> 0.17) to avoid BACKPORTED warning.
But `sidekiq '2.7'` using `celluloid '0.12.0'` in which `require 'celluloid/current'` not supported.

**Comment by pboling** [comment]
This is where the library could branch off a `legacy-2.7` for those who need to point at the last code working with old versions of sidekiq.  Then `master` can continue to work towards compatibility with 4.2, which we also do not yet have it seems (only 4.1 is supported).

**Comment by tarun-pacifica** [comment]
In the main page you dont mention what version of rails the current version supports. Based on @pboling 's comments above am I reading this right that only rails 4.1 is supported?

I am using rails 4.2, are there any major issues with using sidekiq-status with this version?

Thanks.

**Comment by kenaniah** [comment]
We've since removed the `celluloid` dependency, so Sidekiq 2.7 should once again be fully supported. Please let us know (in a new issue) if you run into any other problems. Thanks!
