### ISSUE TITLE
compatibility with delayed extension

### ISSUE THREAD

**Issue by vipulkhullar** [utgarda/sidekiq-status#96]
hi all,
 I am using delayed job extension for sidekiq and want to use the sidekiq status gem to know status of each job
![screenshot from 2017-03-09 15 32 36](https://cloud.githubusercontent.com/assets/20392223/23745312/c03c1064-04dd-11e7-88b0-ada6b3760441.png)
 Sidekiq has processed all the jobs but the status is showing queued only .Please tell whether the gem is compatible with delayed job since now worker/jid is coming in the view.
Redis 3.2
rails 3.2.21
sidekiq 4.2.1

**Comment by axelbox** [comment]
Hi, I have the same problem here. I use the `delayed` function, but when I check `Sidekiq::Status::status(job_id)` I always get `:queued`.
Then in the GUI I see the job running, but status is still queued, and after the job finished - still queued.
sidekiq 3.3.4
sidekiq-status 0.5.3
Rails 3.2.16
redis 3.2.1
Thanks for any help!

**Comment by kenaniah** [comment]
@vipulkhullar @axelbox thanks for the bug report. I'd like to dive into this and figure out what's going on, but could I ask one of you to create a minimized public Github project that reproduces this issue? 

Also, a pull request (with tests) would also be welcome 😉.

**Comment by GaudamThiyagarajan** [comment]
Has this issue been fixed.

**Comment by kenaniah** [comment]
It may have been fixed with the 0.8.0 release, but I haven't heard back from the @vipulkhullar or @axelbox just yet. I'll close the issue if I don't hear back from someone within a few days.
