### ISSUE TITLE
Understanding storage/retrieval

### ISSUE THREAD

**Issue by CharlieHawker** [utgarda/sidekiq-status#97]
Hi,

I'm trying to use the gem with ActiveJob, configured to use sidekiq as the queue adapter per the Sidekiq docs:

`config.active_job.queue_adapter = :sidekiq`

Here's the Job I've created (which runs fine and completes):

```
class GeneratePurchaseOrderPdfJob < ApplicationJob

  include Sidekiq::Status::Worker

  queue_as :default

  def perform(order)
    @order = order
    generate_pdf!
    @order.update_attribute(:purchase_order_pdf, @file)

    # Expose the URL of the generated PDF
    pdf_url = @order.purchase_order_pdf.url
    store url: pdf_url

    Rails.logger.debug("Before")
    Rails.logger.debug(retrieve :url)
    Rails.logger.debug("After")
  end

  def generate_pdf!
    pdf = PurchaseOrderPdf.new(@order)
    data = pdf.render
    @file = StringIO.new(data)
    @file.class.class_eval { attr_accessor :original_filename, :content_type }
    @file.original_filename = "purchase_order-#{@order.order_number}.pdf"
    @file.content_type = "application/pdf"
  end

end
```

The issue I have though is that whilst I can store and retrieve the "url" parameter successfully within the Job (logging out the result of `retrieve :url` successfully shows what I set it to), I cannot seem to get anything except _updated_ and _status_ in the data hash when I try to use either `Sidekiq::Status.get_all jid` or `Sidekiq::Status.get jid, :url` from another controller or the console.

Here's an excerpt of the log output proving that the data is at least stored and retrieved successfully during the job's lifecycle:

```
[ActiveJob] [GeneratePurchaseOrderPdfJob] [9a411aeb-11ee-46c9-996b-4a22e2cb0103] Before
[ActiveJob] [GeneratePurchaseOrderPdfJob] [9a411aeb-11ee-46c9-996b-4a22e2cb0103] //s3-eu-west-2.amazonaws.com/[S3_BUCKET_NAME]/orders/purchase_order_pdfs/000/000/013/original/purchase_order-TSRK0010.pdf?1489152563
[ActiveJob] [GeneratePurchaseOrderPdfJob] [9a411aeb-11ee-46c9-996b-4a22e2cb0103] After
[ActiveJob] [GeneratePurchaseOrderPdfJob] [9a411aeb-11ee-46c9-996b-4a22e2cb0103] Performed GeneratePurchaseOrderPdfJob from Sidekiq(default) in 229.45ms
```

I don't really understand why given the README seems to imply that it should persist, even after the job has completed. Any pointers to something I'm missing? I have the same sidekiq.rb initializer code as detailed in the READMe.

**Comment by CharlieHawker** [comment]
Further to this; if I use a standalone sidekiq worker rather than an ActiveJob job that uses sidekiq, I seem to be able to do as I intend, but I'd just like some clarity as to why it doesn't work via ActiveJob, and perhaps suggest the documentation for sidekiq-status be updated to highlight this caveat for others?

**Comment by cuongnm265** [comment]
+1 here

**Comment by kenaniah** [comment]
This should now be completely fixed in https://github.com/utgarda/sidekiq-status/commit/fcd820e8870a5ced9fd12c7e9db2690a2ec25e72. I'll close this issue out when the next version of the gem is released.
