### ISSUE TITLE
Sidekiq::Status keeps being :queued even after job successfully retried

### ISSUE THREAD

**Issue by lfarcy** [utgarda/sidekiq-status#98]
I've got a job that fails to run and exits with a non-standard error the first time it gets executed.

Since the Sidekiq retry feature is enabled on the worker, the job gets pushed in the retries queue and successfully runs on the second attempt (a few seconds or minutes later).

Unfortunately, the status returned by `Sidekiq::Status` keeps being `:queued`. It behaves as if the job, when retried, skips the sidekiq-status server middleware and never updates the status in the Redis storage.

Is it an expected behavior ? A bug ? I thought Sidekiq retries would be gently managed by this gem.

Thx for your answer(s).

**Comment by lfarcy** [comment]
I found why the status kept being `:queued`. The job did not get retried as I thought in the first place. Actually, the worker class failed to be loaded because of an unexpected circular dependency. The `perform` method was not called. And the server middleware chain was bypassed (no retry, no status update).

I guess this is a case that is not so well managed by Sidekiq itself. The job is lost somehow.

Having said that, I made a few tests to better understand how Sidekiq and Sidekiq::Status behave in case of error and retries. Which brought me to those 2 comments

1. `sidekiq-status` server middleware does not catch non `StandardError` exception as far as I can see. It simply `rescue`s any "exception" raised by the worker but omits to specify any exception class. In this situation, Ruby only catches `StandardError`s and let other exceptions go away. I feel like those exceptions should be caught too and `sidekiq-status` should flag the job as `:failed`. I know it's a bad habit to catch all the exceptions ([Why is it a bad style to `rescue Exception => e` in Ruby?](http://stackoverflow.com/questions/10048173/why-is-it-a-bad-style-to-rescue-exception-e-in-ruby)) but, here, we don't hide the exception but rather temporarily intercepts it to update the status then raise it again.
2. A retryable job that has failed but is waiting for being enqueued again, is marked as `:failed`. Therefore, one cannot make the difference between a job that has definitively failed and a job that may still successfully complete. I saw the wiki page about the "hack" for retry. I will use it as a workaround from now on. But, I strongly feel like the gem should introduce a `:retrying` state that would solve this ambiguity. I can submit a PR if you feel it would be helpful.

**Comment by kenaniah** [comment]
@lfarcy I think a PR (with tests) for this would be very helpful. I am now assisting with the maintenance of this gem, and am looking to get all of the outstanding issues cleaned up in preparation for an updated release. Would you still be interested in making that PR happen?

**Comment by lfarcy** [comment]
@kenamiah Thnx for following up on this issue. And maintaining the gem.

I can definitively take time and try to submit a PR. When would you like this updated release to be code-complete?

**Comment by kenaniah** [comment]
Thanks! As soon as you can get around to it, but feel free to take your time. 

The 0.7.0 release will most likely happen in the near future. That said, I'd be more than happy to release this PR when finished as 0.8.0, even if its the first feature post-0.7.0 to land.

My plan going forward is to create releases as they make sense.

**Comment by lfarcy** [comment]
Hi @kenaniah. I'm moving forward on a PR. I'm also catching up with the latest commits.

For v0.7.0, you moved to appraisals which looks like a simple yet powerful solution for testing the gem over different versions of Sidekiq.

I successfully ran `bundle exec appraisal install` to install all the dependencies `sidekiq-status` now needs to run the test suite over multiple versions of Sidekiq. But, when I try to run `bundle exec appraisal rake test` to run the tests over all the configured appraisals, I only get failures. 

The root cause is an absence of a local Redis server, as far as I understand. I somehow expected the test suite would start a Redis server when required and stop it at the end. How is it supposed to work? What CLI do you use to start Redis? Which version?

Thx for your help.

**Comment by kenaniah** [comment]
I develop on a mac, so if you have homebrew installed, the following should do the trick:

```bash
brew tap homebrew/services
brew install redis
brew services start redis
```

**Comment by lfarcy** [comment]
@kenaniah I've just submitted the PR. I'd appreciate if you could have a look and give feedbacks.

Not mergeable as is since tests still malfunctioning for Sidekiq 3.x and 5.x. I don't quite understand how `confirmations_thread` actually behaves.

**Comment by kenaniah** [comment]
Thanks for the PR! My workload is a bit high this week, but I'll try digging into the test suite side of things to figure out what's going on over the next few days. Looks like a great start though.

**Comment by lfarcy** [comment]
I totally understand. Tell me when you move forward. 

Please note that, due to how the server middleware has to be positioned in the middleware chain for Sidekiq v3.x and v4.x, I had to modify how `Sidekiq::Status` is configured. In a non backwards-compatible way.
